name: Step Types

on:
  workflow_dispatch:
    
# Jobs runs in parralel
# bash, python, and external action are different types of steps
# needs is used to make sure that the specified step runs before the python step
jobs:
  say-hello-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello World"

  say-hello-python:
    runs-on: ubuntu-24.04
    needs:
      - say-hello-bash
    steps:
      - run: print("Hello World")
        shell: python
    
  # External Action
  say-hello-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/hello-world-javascript-action@081a6d193d1dcb38460df1e6927486d748730f9d
        with:
          who-to-greet: "World"