name: Step Types

on:
  workflow_dispatch:
    
# Jobs runs in parralel
jobs:
  say-hello-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello World"

  say-hello-python:
    runs-on: ubuntu-24.04
    steps:
      - run: print("Hello Worls")
        shell: python
    
  # External Action
  say-hello-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: git@github.com:MovinduLochana/Workflows-and-Action.git
        with:
          who-to-greet: "World"